"""DSPy-based code generator using ProgramOfThought.

Architecture
------------
Uses ``dspy.ProgramOfThought`` — DSPy's built-in generate→execute→retry
pipeline — instead of manually wiring ChainOfThought + fix loops.

``ProgramOfThought`` internally:

1. **Generates** code via ``ChainOfThought`` from our declarative signature.
2. **Executes** it through a pluggable interpreter (our :class:`FHIRInterpreter`).
3. **Self-heals** — if execution fails, it feeds the error back and regenerates
   (up to ``max_iters``).
4. **Produces** a final answer by reasoning over the code output.

We supply:

- **Signature docstring** → task description (becomes the system prompt).
- **Input fields** → requirement + clinical context (FHIR spec, import guide, rules).
- **Output fields** → the FHIR resources JSON list.
- **Few-shot demos** → curated (requirement → code) pairs.
- **FHIRInterpreter** → adapter that delegates to our :class:`Executor` backends
  (local subprocess, Dify sandbox, E2B cloud).
"""

from __future__ import annotations

import json
import logging
from typing import Any, cast

import dspy  # type: ignore[import-untyped]

from fhir_synth.code_generator.executor import Executor, LocalSubprocessExecutor
from fhir_synth.code_generator.few_shot_examples import ALL_EXAMPLES
from fhir_synth.code_generator.metrics import calculate_code_quality_score
from fhir_synth.code_generator.prompts import _SANDBOX_SECTION, clinical_rules
from fhir_synth.fhir_spec import import_guide, spec_summary

logger = logging.getLogger(__name__)


# ==============================================================================
# DSPy Signature — purely declarative, no hand-written prompt text
# ==============================================================================


class FHIRResourceGeneration(dspy.Signature):  # type: ignore[misc]
    """Given a natural-language requirement and FHIR reference context,
    write and execute Python code that creates valid FHIR R4B resources.

    The code MUST:
    - Define exactly: def generate_resources() -> list[dict]
    - Import from fhir.resources.R4B (see context for exact module paths)
    - Call .model_dump(exclude_none=True) on every Pydantic model
    - Use uuid4() for resource IDs and Decimal for numeric values
    - Use real clinical codes (ICD-10, LOINC, RxNorm, SNOMED CT)
    - Use Faker for realistic patient demographics
    - Return a flat list of resource dicts
    - Print the final JSON list via: print(json.dumps(generate_resources()))
    """

    # --- Inputs (dynamic per call) ---
    requirement: str = dspy.InputField(
        desc="Natural language description of FHIR resources to generate"
    )
    context: str = dspy.InputField(
        desc=(
            "Reference context: sandbox constraints, FHIR import guide, "
            "resource field specs, and clinician-authored rules for "
            "comorbidity patterns, medication codes, vital-sign ranges, "
            "SDOH codes, encounter types, and data-quality variation"
        )
    )

    # --- Output ---
    resources: str = dspy.OutputField(
        desc="JSON list of FHIR resource dicts produced by the executed code"
    )


# ==============================================================================
# FHIRInterpreter — adapter bridging our Executor to DSPy's interpreter API
# ==============================================================================


class FHIRInterpreter:
    """Adapter that makes our: class:`Executor` look like DSPy's interpreter.

    ``ProgramOfThought`` calls ``interpreter.execute(code)`` and expects
    either a raw result or a ``FinalOutput``.  We delegate to our own
    executor and return the artifacts as a JSON string.
    """

    def __init__(self, executor: Executor, timeout: int = 30) -> None:
        self._executor = executor
        self._timeout = timeout

    def execute(self, code: str) -> str:
        """Execute code via our Executor and return JSON output.

        The code generated by ProgramOfThought may not define
        ``generate_resources()`` — it might just print output directly.
        We wrap it so the executor can handle it.
        """
        result = self._executor.execute(code, timeout=self._timeout)
        return json.dumps(result.artifacts)

    def shutdown(self) -> None:
        """Clean up resources (no-op for most backends)."""


# ==============================================================================
# Context builder — assembles the reference material once
# ==============================================================================


def _build_generation_context() -> str:
    """Assemble all reference context into a single string.

    This is passed as the ``context`` input field.  DSPy handles
    formatting; we just provide the raw content.
    """
    return "\n\n".join(
        [
            _SANDBOX_SECTION,
            f"IMPORT GUIDE:\n{import_guide()}",
            f"FHIR SPEC:\n{spec_summary()}",
            f"CLINICAL RULES:\n{clinical_rules()}",
        ]
    )


# ==============================================================================
# Few-shot demos — this is where clinical knowledge is *demonstrated*
# ==============================================================================


def _build_demos(context: str) -> list[dspy.Example]:
    """Build DSPy Example objects from the curated few-shot examples.

    Each example shows the LLM a complete (requirement → code → resources) triple.
    The ``context`` is attached, so demos and live calls share the same field.
    """
    demos = []
    for ex in ALL_EXAMPLES:
        demo = dspy.Example(
            requirement=ex["requirement"],
            context=context,
            resources="[{...}]",  # placeholder — ProgramOfThought fills real output
        ).with_inputs("requirement", "context")
        demos.append(demo)
    return demos


# ==============================================================================
# LiteLLM Adapter — bridges our LLMProvider to DSPy's LM interface
# ==============================================================================


class LiteLLMAdapter(dspy.LM):  # type: ignore[misc]
    """Adapter that lets DSPy call our LiteLLM-based LLMProvider."""

    def __init__(self, llm_provider: Any) -> None:
        super().__init__(model=llm_provider.model)
        self.provider = llm_provider
        self.history: list[dict[str, Any]] = []

    def __call__(
        self,
        prompt: str | None = None,
        messages: list[dict[str, str]] | None = None,
        **kwargs: Any,
    ) -> list[str]:
        if prompt and not messages:
            messages = [{"role": "user", "content": prompt}]
        elif not messages:
            raise ValueError("Either prompt or messages must be provided")

        system_msg = None
        user_parts: list[str] = []
        for msg in messages:
            if msg["role"] == "system":
                system_msg = msg["content"]
            elif msg["role"] == "user":
                user_parts.append(msg["content"])

        response = self.provider.generate_text(
            prompt="\n\n".join(user_parts),
            system=system_msg,
        )

        self.history.append({"messages": messages, "response": response})
        return [response]

    def inspect_history(self, n: int = 1) -> list[dict[str, Any]]:
        return self.history[-n:]


# ==============================================================================
# Public API
# ==============================================================================


class DSPyCodeGenerator:
    """Code generator using DSPy ProgramOfThought.

    How it works
    ------------
    1. **Declarative signature** defines input/output specs — no hand-written prompts.
    2. **Few-shot demos** teach correct patterns (imports, model_dump, codes, Faker).
    3. **Context field** gives the LLM the full clinician-authored reference
       (FHIR spec, import guide, clinical rules) without hardcoding it into prompts.
    4. **ProgramOfThought** generates code, executes it via our ``FHIRInterpreter``,
       and automatically retries with error feedback on failure.
    """

    def __init__(
        self,
        llm_provider: Any,
        max_retries: int = 3,
        enable_scoring: bool = False,
        executor: Executor | None = None,
    ) -> None:
        self.lm = LiteLLMAdapter(llm_provider)
        dspy.settings.configure(lm=self.lm)

        self.max_retries = max_retries
        self.enable_scoring = enable_scoring
        self.executor: Executor = executor or LocalSubprocessExecutor()

        # Build the ProgramOfThought module with our custom interpreter
        self._context = _build_generation_context()
        # FHIRInterpreter is duck-type compatible with PythonInterpreter
        # (implements .execute() and .shutdown())
        interpreter = cast(dspy.PythonInterpreter, cast(object, FHIRInterpreter(self.executor)))
        self.pot = dspy.ProgramOfThought(
            FHIRResourceGeneration,
            max_iters=max_retries,
            interpreter=interpreter,
        )
        # Attach few-shot demos to the internal code_generate predictor
        self.pot.code_generate.demos = _build_demos(self._context)

    def generate(self, prompt: str) -> list[dict[str, Any]]:
        """Generate FHIR resources from a natural language prompt.

        Uses ``ProgramOfThought`` end-to-end: generates code, executes it
        through our ``FHIRInterpreter``, retries on failure, and returns
        the parsed resource list.
        """
        prediction = self.pot(requirement=prompt, context=self._context)

        # ProgramOfThought produces the final output as a string
        raw = prediction.resources
        resources: list[dict[str, Any]] = json.loads(raw) if isinstance(raw, str) else raw

        if self.enable_scoring:
            # Score against the last generated code if available
            code = getattr(prediction, "final_generated_code", "")
            if code:
                metrics = calculate_code_quality_score(code, resources)
                logger.info(
                    "Code quality: %.2f (%s)",
                    metrics["score"],
                    metrics["grade"],
                )

        return resources

    def generate_code_from_prompt(self, prompt: str) -> str:
        """Generate Python code only (without executing it).

        Falls back to a simple ``ChainOfThought`` call since
        ``ProgramOfThought`` always executes.
        """
        from fhir_synth.code_generator.utils import extract_code

        cot = dspy.ChainOfThought(FHIRResourceGeneration)
        cot.demos = _build_demos(self._context)
        prediction = cot(requirement=prompt, context=self._context)
        # ProgramOfThought's code_generate would have produced code;
        # with ChainOfThought we get the resources field with embedded code
        return extract_code(prediction.resources)

    def execute_generated_code(self, code: str, timeout: int = 30) -> list[dict[str, Any]]:
        """Execute pre-generated code through our executor.

        This bypasses ProgramOfThought and uses the executor directly,
        useful when you already have code (e.g. from ``--save-code``).
        """
        result = self.executor.execute(code, timeout=timeout)
        resources = result.artifacts

        if self.enable_scoring:
            metrics = calculate_code_quality_score(code, resources)
            logger.info(
                "Code quality: %.2f (%s)",
                metrics["score"],
                metrics["grade"],
            )

        return resources

    @staticmethod
    def apply_metadata_to_resources(
        resources: list[dict[str, Any]],
        security: list[dict[str, Any]] | None = None,
        tag: list[dict[str, Any]] | None = None,
        profile: list[str] | None = None,
        source: str | None = None,
    ) -> list[dict[str, Any]]:
        """Apply FHIR Meta fields to resources."""
        for resource in resources:
            if not any([security, tag, profile, source]):
                continue

            meta = resource.setdefault("meta", {})

            if security:
                meta["security"] = meta.get("security", []) + security
            if tag:
                meta["tag"] = meta.get("tag", []) + tag
            if profile:
                meta["profile"] = meta.get("profile", []) + profile
            if source:
                meta["source"] = source

        return resources
